#!/usr/bin/env python

import sys

from iiwas_rqt.iiwas_manager import IiwasManager
from rqt_gui.main import Main

plugin = 'iiwas_rqt'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))