import json

def open_json(filename) -> list:
    '''
        Open the json file which stores the path
    '''
    f = open(filename, )
    data = json.load(f)
    trajectory = data['trajectories'][0]['positions']

    # Iterating through the json
    # list
    # for i in data['trajectories'][0]['positions']:
    # 	print(i)

    f.close()
    num_path_points = len(trajectory)

    return trajectory, num_path_points

def get_x_y_traj(trajectory) -> list:
    '''
        Get the 2d trajectory which is generated by RRTstar in MoveIt
    '''
    length = len(trajectory)
    xy_traj = [[0, 0] for i in range(length)]
    for i in range(length):
        xy_traj[i] = trajectory[i][:2]

    return xy_traj


def check_arrive(self) -> bool:
    '''
        According to self.end_point_threshold=0.01 -> check the robot arrive at the target position or not
    '''
    curren_state = self.get_robot_current_state()
    curren_position = curren_state[0]
    cur_dist = self.compute_euclidean_distance(self.end_point, curren_position)

    if cur_dist < self.end_point_threshold:
        return True